/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RMIService;

import java.awt.Color;
import java.rmi.registry.LocateRegistry;
import javax.swing.JOptionPane;

/**
 *
 * @author WINDOWS
 */
public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
       
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bookA = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        up = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        em = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        c3 = new javax.swing.JRadioButton();
        c4 = new javax.swing.JRadioButton();
        update = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        ap1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        timee = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        aid = new javax.swing.JTextField();
        datee = new com.toedter.calendar.JDateChooser();
        jLabel22 = new javax.swing.JLabel();
        c1 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        book = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        searcht = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        yourinfo = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(139, 231, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS\\Downloads\\patient (6).png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Patients");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS\\Downloads\\gradient (3).png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        addP.setBackground(new java.awt.Color(139, 231, 253));
        addP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addPMouseMoved(evt);
            }
        });
        addP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPMouseExited(evt);
            }
        });
        addP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS\\Downloads\\medical (1).png")); // NOI18N
        addP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Patient");
        addP.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, -1, 30));

        jPanel1.add(addP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        bookA.setBackground(new java.awt.Color(139, 231, 253));
        bookA.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bookAMouseMoved(evt);
            }
        });
        bookA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookAMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookAMouseExited(evt);
            }
        });
        bookA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS\\Downloads\\medical (3).png")); // NOI18N
        bookA.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Book Appointment");
        bookA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel1.add(bookA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 50));

        pi.setBackground(new java.awt.Color(139, 231, 253));
        pi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                piMouseMoved(evt);
            }
        });
        pi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piMouseExited(evt);
            }
        });
        pi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS\\Downloads\\patient (8).png")); // NOI18N
        pi.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Patient Info");
        pi.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jPanel1.add(pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\WINDOWS\\Downloads\\gradient (3).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 540, 70));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("PatientID :");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 20));

        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        jPanel5.add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Phone Number :");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Last Name :");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));
        jPanel5.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("First Name :");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        jPanel5.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 130, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Gender :");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, 20));

        em.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emActionPerformed(evt);
            }
        });
        jPanel5.add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 130, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Email :");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, 20));

        pn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnActionPerformed(evt);
            }
        });
        jPanel5.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 130, -1));

        buttonGroup1.add(c3);
        c3.setText("Male");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel5.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        buttonGroup1.add(c4);
        c4.setText("Female");
        jPanel5.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        update.setBackground(new java.awt.Color(0, 137, 185));
        update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                updateMouseMoved(evt);
            }
        });
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateMouseExited(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel5.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 150, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Date of Birth :");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        jPanel5.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 130, -1));

        ap1.setBackground(new java.awt.Color(0, 137, 185));
        ap1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ap1.setForeground(new java.awt.Color(255, 255, 255));
        ap1.setText("ADD");
        ap1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ap1MouseMoved(evt);
            }
        });
        ap1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ap1MouseExited(evt);
            }
        });
        ap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ap1ActionPerformed(evt);
            }
        });
        jPanel5.add(ap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 150, 30));

        jLabel11.setText("( this info is required only if you want to update)");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Visit Type :");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Time :");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 20));
        jPanel6.add(timee, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("AppointmentID :");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));
        jPanel6.add(aid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 252, 120, 30));
        jPanel6.add(datee, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 120, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Date :");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 20));

        buttonGroup2.add(c1);
        c1.setText("General Checkup");
        jPanel6.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        buttonGroup2.add(c2);
        c2.setText("Medical Consultation");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel6.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 121, -1, 20));

        book.setBackground(new java.awt.Color(0, 137, 185));
        book.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        book.setForeground(new java.awt.Color(255, 255, 255));
        book.setText("Book");
        book.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bookMouseMoved(evt);
            }
        });
        book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookMouseExited(evt);
            }
        });
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jPanel6.add(book, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 190, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("PatientID :");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 20));
        jPanel6.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, -1));

        cancel.setBackground(new java.awt.Color(0, 137, 185));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.setToolTipText("");
        cancel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cancelMouseMoved(evt);
            }
        });
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel6.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 100, 30));

        jTabbedPane1.addTab("tab2", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 137, 185));
        jLabel12.setText("your Informations ");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel25.setText("PatientID :");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));
        jPanel7.add(searcht, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, 30));

        search.setBackground(new java.awt.Color(0, 137, 185));
        search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel7.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 100, 30));
        jPanel7.add(yourinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 540, 220));

        jTabbedPane1.addTab("tab3", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 540, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void emActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emActionPerformed

    private void pnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:

    if (fn.getText().equals("") || ln.getText().equals("") || dob.getDate() == null || em.getText().equals("") || pn.getText().equals("") || up.getText().equals("") || (!c4.isSelected() && !c3.isSelected())) {
        JOptionPane.showMessageDialog(null, "Please enter all your information!");
    } else {
        Patient p = new Patient();
        p.FirstName = fn.getText();
        p.LastName = ln.getText();
        p.DateOfBirth = new java.sql.Date(dob.getDate().getTime());
        p.Email = em.getText();
        p.PhoneNumber = pn.getText();
        if (c3.isSelected())
            p.Gender = "Male";
        else
            p.Gender = "Female";
        p.MedicalHistory = "";
        p.DiagnosisDetails = "";
        p.PrescriptionDetails = "";

        int patientID = 0;
        try {
            patientID = Integer.parseInt(up.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Patient ID. Please enter a valid integer.");
            return; // Exit the method if the Patient ID is not a valid integer
        }

        try {
            // RMI
            PatientManagementService patientManagement = (PatientManagementService) LocateRegistry.getRegistry("localhost", 1098).lookup("PatientManagement");
            boolean success = patientManagement.updatePatientInfo(patientID, p);
            if (success) {
                JOptionPane.showMessageDialog(null, "Patient updated successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Update failed");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    }//GEN-LAST:event_updateActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void addPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPMouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_addPMouseClicked

    private void addPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPMouseMoved
        addP.setBackground(new Color(0x02, 0xC7, 0xF7));
    }//GEN-LAST:event_addPMouseMoved

    private void addPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPMouseExited
        addP.setBackground(new Color(139,231,253));
    }//GEN-LAST:event_addPMouseExited

    private void bookAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookAMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_bookAMouseClicked

    private void bookAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookAMouseExited
        bookA.setBackground(new Color(139,231,253));
    }//GEN-LAST:event_bookAMouseExited

    private void bookAMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookAMouseMoved
       bookA.setBackground(new Color(0x02, 0xC7, 0xF7));
    }//GEN-LAST:event_bookAMouseMoved

    private void piMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piMouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_piMouseClicked

    private void piMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piMouseMoved
         pi.setBackground(new Color(0x02, 0xC7, 0xF7));
    }//GEN-LAST:event_piMouseMoved

    private void piMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piMouseExited
       pi.setBackground(new Color(139,231,253));
    }//GEN-LAST:event_piMouseExited

    private void updateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseMoved
        update.setBackground(new Color(139,231,253));
    }//GEN-LAST:event_updateMouseMoved

    private void bookMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseMoved
        book.setBackground(Color.green);
    }//GEN-LAST:event_bookMouseMoved

    private void cancelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseMoved
       cancel.setBackground(Color.red);
    }//GEN-LAST:event_cancelMouseMoved

    private void bookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMouseExited
        book.setBackground(new Color(0,137,185));
    }//GEN-LAST:event_bookMouseExited

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
       cancel.setBackground(new Color(0,137,185));
    }//GEN-LAST:event_cancelMouseExited

    private void updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseExited
    update.setBackground(new Color(0,137,185));
    }//GEN-LAST:event_updateMouseExited

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
String patientID = id.getText();
java.util.Date utilDate = datee.getDate();
 java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
 String time = timee.getText();
  String visitType = "";
  if (c1.isSelected()) {
            visitType = "General Checkup";
        } else if (c2.isSelected()) {
            visitType = "Medical Consultation";
        }
  try {
            // Replace "AppointmentService" with the actual name of your RMI service interface
            AppointmentService appointmentService = (AppointmentService) LocateRegistry.getRegistry("localhost", 1099).lookup("AppointmentService");
            int appointmentID = appointmentService.bookAppointment(patientID, sqlDate, time, visitType,"");
if (appointmentID!=-1) {
                JOptionPane.showMessageDialog(null, "Appointment added seccefuly AppointmentID : "+ appointmentID);
            } else {
                JOptionPane.showMessageDialog(null, "Failed");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
 

    }//GEN-LAST:event_bookActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void ap1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap1MouseMoved
        // TODO add your handling code here:
        ap1.setBackground(Color.GREEN);
    }//GEN-LAST:event_ap1MouseMoved

    private void ap1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ap1MouseExited
        // TODO add your handling code here:
        ap1.setBackground(new Color(0,137,185));
    }//GEN-LAST:event_ap1MouseExited

    private void ap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap1ActionPerformed
        // TODO add your handling code here:
        if (fn.getText().equals("") || ln.getText().equals("") || dob.getDate() == null || em.getText().equals("") || pn.getText().equals("") || (!c4.isSelected() && !c3.isSelected())) {
    JOptionPane.showMessageDialog(null, "Please enter all your informations!");
} else {
      Patient p = new Patient();
      p.FirstName = fn.getText();
      p.LastName = ln.getText();
      p.DateOfBirth = new java.sql.Date(dob.getDate().getTime());
      p.Email = em.getText(); 
      p.PhoneNumber = pn.getText();
      if(c3.isSelected()) 
      p.Gender = "Male";
      else 
      p.Gender = "Female";
      
      try {
      
        //RMI
        PatientManagementService patientManagement = (PatientManagementService) LocateRegistry.getRegistry("localhost",1098).lookup("PatientManagement");
        int patientID = patientManagement.addPatient(p);
    if (patientID != -1) {
        JOptionPane.showMessageDialog(null, "Patient added successfully. PatientID: " + patientID);
    } else {
        JOptionPane.showMessageDialog(null, "Failed to add patient");
    }
} catch (Exception ex) {
    ex.printStackTrace();}
}
        
    }//GEN-LAST:event_ap1ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        if(aid.getText().equals(""))
           JOptionPane.showMessageDialog(null,"Please Enter the ID of the appointmet you want to cancel");
        
        else {
       
        int appointmentID = Integer.parseInt( aid.getText());
        try {
         //Rmi 
         AppointmentService appointmentService = (AppointmentService) LocateRegistry.getRegistry("localhost",1099).lookup("AppointmentService");
         boolean success = appointmentService.cancelAppointment(appointmentID);
         if(success)
             JOptionPane.showMessageDialog(null, "Appointment canceled seccessfully");
         else 
             JOptionPane.showMessageDialog(null, "Appointment canceling Failed"); 
        
        } catch (Exception ex) {
    ex.printStackTrace();}
        
        }
        
    }//GEN-LAST:event_cancelActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
         if (searcht.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Please enter Patient ID!");
    } else {
        int patientID = 0;

        try {
            patientID = Integer.parseInt(searcht.getText());
            // RMI
            PatientManagementService patientManagement = (PatientManagementService) LocateRegistry.getRegistry("localhost", 1098).lookup("PatientManagement");

            // Search for the patient using the entered ID
            Patient patient = patientManagement.searchPatient(patientID);

            if (patient != null) {
                // Display patient information in the JTextArea
               yourinfo.setText("First Name:"+patient.FirstName+"\n"+"Last Name : " + patient.LastName+"\n"+"Date of Birth :"+patient.DateOfBirth+"\n"
               + "Email : "+patient.Email+"\n"+"Gender :"+patient.Gender+"\n"+"Phone Number : "+patient.PhoneNumber+"\n"+"MedicalHistory : "+patient.MedicalHistory+"\n"+"Diagnosis Details : "+patient.DiagnosisDetails+"\n"+"Prescription Details : "+patient.PrescriptionDetails);
                 
                JOptionPane.showMessageDialog(null, "Patient found!");
            } else {
                // Handle the case where the patient is not found
                JOptionPane.showMessageDialog(null, "Patient not found!");
            }
        } catch (NumberFormatException e) {
            // Handle the case where the text is not a valid integer
            e.printStackTrace(); // or display an error message
        } catch (Exception ex) {
            ex.printStackTrace();
        }}
         
    }//GEN-LAST:event_searchActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ClientGUI f = new ClientGUI();
        f.setVisible(true);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addP;
    private javax.swing.JTextField aid;
    private javax.swing.JButton ap1;
    private javax.swing.JButton book;
    private javax.swing.JPanel bookA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JRadioButton c4;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser datee;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField em;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField ln;
    private javax.swing.JPanel pi;
    private javax.swing.JTextField pn;
    private javax.swing.JButton search;
    private javax.swing.JTextField searcht;
    private javax.swing.JTextField timee;
    private javax.swing.JTextField up;
    private javax.swing.JButton update;
    private java.awt.TextArea yourinfo;
    // End of variables declaration//GEN-END:variables
}
